export enum TransactionFlowType {
  // Bridge
  BRIDGE_IN = "BRIDGE_IN",
  BRIDGE_OUT = "BRIDGE_OUT",
  // LP
  AMBIENT_LIQUIDITY_TX = "AMBIENT_LIQUIDITY_TX",
  CANTO_DEX_LP_TX = "CANTO_DEX_LP_TX",
  STAKE_LP_TX = "STAKE_LP_TX",
  CLAIM_LP_REWARDS_TX = "CLAIM_LP_REWARDS_TX",
  // CLM
  CLM_CTOKEN_TX = "CLM_CTOKEN_TX",
  CLM_CLAIM_REWARDS_TX = "CLM_CLAIM_REWARDS_TX",
}
