import { Theme } from "@rainbow-me/rainbowkit";

export const candoTheme: Theme = {
  //   lightMode: {
  blurs: {
    modalOverlay: "blur(2px)",
  },
  colors: {
    accentColor: "var(--primary-90-color)",
    accentColorForeground: "var(--canto-color)",
    actionButtonBorder: "var(--text-dark-30-color)",
    actionButtonBorderMobile: "var(--text-dark-30-color)",
    actionButtonSecondaryBackground: "...",
    closeButton: "...",
    closeButtonBackground: "...",
    connectButtonBackground: "var(--card-surface-color)",
    connectButtonBackgroundError: "...",
    connectButtonInnerBackground: "...",
    connectButtonText: "var(--primary-90-color)",
    connectButtonTextError: "...",
    connectionIndicator: "...",
    downloadBottomCardBackground: "...",
    downloadTopCardBackground: "...",
    error: "...",
    generalBorder: "var(--text-dark-30-color)",
    generalBorderDim: "...",
    menuItemBackground: "...",
    modalBackdrop: "...",
    modalBackground: "var(--card-surface-color)",
    modalBorder: "var(--text-dark-30-color)",
    modalText: "...",
    modalTextDim: "...",
    modalTextSecondary: "...",
    profileAction: "...",
    profileActionHover: "...",
    profileForeground: "...",
    selectedOptionBorder: "transparent",
    standby: "...",
  },
  fonts: {
    body: "Proto Mono",
  },
  radii: {
    actionButton: "var(--border-radius, 0)",
    connectButton: "var(--border-radius, 0)",
    menuButton: "var(--border-radius, 0)",
    modal: "var(--border-radius, 0)",
    modalMobile: "var(--border-radius, 0)",
  },
  shadows: {
    connectButton: "var(--box-shadow, 3px 3px 0px 0px rgba(17, 17, 17, 0.15))",
    dialog: "var(--box-shadow, 3px 3px 0px 0px rgba(17, 17, 17, 0.15))",
    profileDetailsAction: "...",
    selectedOption: "...",
    selectedWallet: "...",
    walletLogo: "...",
  },
};
//   darkMode: {
//     blurs: {
//       modalOverlay: "blur(2px)",
//     },
//     colors: {
//       accentColor: "var(--canto-color)",
//       accentColorForeground: "var(--card-surface-color)",
//       actionButtonBorder: "var(--text-dark-30-color)",
//       actionButtonBorderMobile: "var(--text-dark-30-color)",
//       actionButtonSecondaryBackground: "...",
//       closeButton: "...",
//       closeButtonBackground: "...",
//       connectButtonBackground: "var(--card-surface-color)",
//       connectButtonBackgroundError: "...",
//       connectButtonInnerBackground: "...",
//       connectButtonText: "var(--primary-90-color)",
//       connectButtonTextError: "...",
//       connectionIndicator: "...",
//       downloadBottomCardBackground: "...",
//       downloadTopCardBackground: "...",
//       error: "...",
//       generalBorder: "var(--text-dark-30-color)",
//       generalBorderDim: "...",
//       menuItemBackground: "...",
//       modalBackdrop: "...",
//       modalBackground: "var(--card-surface-color)",
//       modalBorder: "var(--text-dark-30-color)",
//       modalText: "red",
//       modalTextDim: "blue",
//       modalTextSecondary: "yellow",
//       profileAction: "...",
//       profileActionHover: "...",
//       profileForeground: "...",
//       selectedOptionBorder: "transparent",
//       standby: "...",
//     },
//     fonts: {
//       body: "Proto Mono",
//     },
//     radii: {
//       actionButton: "var(--border-radius, 0)",
//       connectButton: "var(--border-radius, 0)",
//       menuButton: "var(--border-radius, 0)",
//       modal: "var(--border-radius, 0)",
//       modalMobile: "var(--border-radius, 0)",
//     },
//     shadows: {
//       connectButton:
//         "var(--box-shadow, 3px 3px 0px 0px rgba(17, 17, 17, 0.15))",
//       dialog: "var(--box-shadow, 3px 3px 0px 0px rgba(17, 17, 17, 0.15))",
//       profileDetailsAction: "...",
//       selectedOption: "...",
//       selectedWallet: "...",
//       walletLogo: "...",
//     },
//   },
// };
